# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71c7a9e61fc97635682f1136d745fa5c3708412f4f8760edaa8021daefe8b7a8263e2b48f18d042ea323c346b689454dd534e08d00b681f16c3d0b29b06ae183

test:
  secret_key_base: 0c7225c678a00a03f00fcf334237dc8e002ce14d52c15538d0ef8eba47309d090b4489a419aa27a764656fb35e172c7be46d1246f2191be9f85544eac90bd1d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
